{"name": "test_login_url", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestLogin' object has no attribute 'driver'", "trace": "self = <login_test.TestLogin object at 0x000001FAE05757C0>\n\n    @pytest.fixture(scope='function',autouse=True)\n    def setup_login(self):\n>       self.login  =Login_Page(self.driver)\nE       AttributeError: 'TestLogin' object has no attribute 'driver'\n\ntests\\login_test.py:16: AttributeError"}, "description": "Check the Login page", "start": 1730126547545, "stop": 1730126547545, "uuid": "be1ea08e-9cb8-4044-95d6-608e9f9580fc", "historyId": "b708fec5871dfae58d5f00b710a476f6", "testCaseId": "b708fec5871dfae58d5f00b710a476f6", "fullName": "tests.login_test.TestLogin#test_login_url", "labels": [{"name": "severity", "value": "blocker"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "29152-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}