{"name": "test_enter_url", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestSignUp' object has no attribute 'driver'", "trace": "self = <signup_test.TestSignUp object at 0x000001FAE0AE7940>\n\n    @pytest.fixture(scope='function', autouse=True)\n    def signup_fixture(self):\n>       self.sign = SignUp_Page(self.driver)\nE       AttributeError: 'TestSignUp' object has no attribute 'driver'\n\ntests\\signup_test.py:18: AttributeError"}, "description": "Check the SignUp Page", "start": 1730126547772, "stop": 1730126547772, "uuid": "10f5d9a9-194e-4439-b8b7-e8b09221a185", "historyId": "d4d4e4eceb7748e75efe99c044a1f515", "testCaseId": "d4d4e4eceb7748e75efe99c044a1f515", "fullName": "tests.signup_test.TestSignUp#test_enter_url", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "signup_test"}, {"name": "subSuite", "value": "TestSignUp"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "29152-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.signup_test"}]}