{"name": "test_enter_firstname", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestSignUp' object has no attribute 'driver'", "trace": "self = <signup_test.TestSignUp object at 0x000001FAE0AE7190>\n\n    @pytest.fixture(scope='function', autouse=True)\n    def signup_fixture(self):\n>       self.sign = SignUp_Page(self.driver)\nE       AttributeError: 'TestSignUp' object has no attribute 'driver'\n\ntests\\signup_test.py:18: AttributeError"}, "description": "Check the SignUp Page", "start": 1730126547807, "stop": 1730126547807, "uuid": "ad5ae30f-9cf8-4da3-9fce-206bd59cbb8b", "historyId": "6922d279e2c6427dcc820597f10beb3e", "testCaseId": "6922d279e2c6427dcc820597f10beb3e", "fullName": "tests.signup_test.TestSignUp#test_enter_firstname", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "signup_test"}, {"name": "subSuite", "value": "TestSignUp"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "29152-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.signup_test"}]}